name: Auto Deploy

on:
  push:
    branches:
      - main  # Se activará cada vez que hagas push en la rama main
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub si lo deseas

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Mensaje de confirmación
        run: echo "🚀 Cambios detectados, se ha ejecutado el despliegue automático"
